// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gen_models

type GetTokenBalancesResponse struct {
	Address string          `json:"address"`
	ChainID int             `json:"chainID"`
	Items   []*TokenBalance `json:"items"`
}

type GetTransactionHistoryResponse struct {
	Address string         `json:"address"`
	ChainID int            `json:"chainID"`
	Items   []*Transaction `json:"items"`
}

type HelloResponse struct {
	Response string `json:"response"`
}

type TokenBalance struct {
	LogoURL              string  `json:"LogoURL"`
	Balance              string  `json:"Balance"`
	ContractTickerSymbol string  `json:"ContractTickerSymbol"`
	ContractDecimals     int     `json:"ContractDecimals"`
	QuoteRate            float64 `json:"QuoteRate"`
}

type Transaction struct {
	TxHash        string `json:"txHash"`
	Successful    bool   `json:"Successful"`
	From          string `json:"From"`
	To            string `json:"To"`
	Value         string `json:"Value"`
	BlockSignedAt string `json:"BlockSignedAt"`
}
